### ISSUE TITLE
Permissions section in .yml file needed

### ISSUE THREAD

**Issue by joshuabrownenz** [pemtajo/badge-readme#20]
I created the specified update-badges.yml

```yml
name: Update badges

on:
  schedule:
    # Runs at 0am UTC every day
    - cron: "0 0 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
```

But when I ran the workflow I was getting a failed action with the error message
`github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents"}`

It looked like it was an issue with the GITHUB_TOKEN so I added the `contents: write` permission in the .yml and the problem went away.

```yml
name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 2 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
```
